#!/bin/sh
# Script that runs on startup, should be linked in /etc/init.d
#
#  ---TODO---
# Things that need to be on the image
#
# - Fail2ban configuration
# - Limit TCP Inbound and Outbound
# - Make sure all permissions are correct
# - Make sure the widget code is in /usr/local/bin and the service running it is in /etc/systemd/system
# - first-boot.txt should be in /etc/
# - this should be in /etc/init.d
# - Make sure this shit works on clea BBB and CC
# - Take master key out of server.py
# - JTAG/Console Access
# First Check to see if its the first boot (does first-boot exist?)

date -s "24 FEB 2016 18:00:00"

if [ -f /etc/first-boot.txt];then
  touch devide_id.txt
  echo $RANDOM$RANDOM$RANDOM > /etc/device_id.txt
  rm /etc/first-boot.txt
else

fi
