#!/bin/bash
#TODO Replace with Docker Startup script

CERT="certs/cert.pem"
KEY="certs/key.pem"

if [ -f $CERT -a -f $KEY ];then
  echo "Certs already exist"
else
  echo "Creating New Certs"
  openssl req -x509 -newkey rsa:2048 -days 100 -nodes -subj "/C=US/ST=Massachusetts/L=Amherst/O=UMass/CN=www.umass.edu"\
  -keyout certs/key.pem -out certs/cert.pem
fi

python server.py
